import { useMemo, useState } from "react";
import { ArrowUpRight, BookOpen, Check, ChevronRight, Database, ExternalLink, FileText, FlaskConical, Image as ImageIcon, Menu, Microscope, Play, Search, Server, X } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { videoResources } from "@/lib/resources";
import { imageResources } from "@/lib/images";

type Page = "home" | "cases" | "videos" | "images" | "methods";
const photos = { lab: "/research/ml-lab.jpg", server: "/research/server-room.jpg", slide: "/research/whole-slide.png" };
const featuredVideos = [
  { title: "But what is a neural network?", source: "3Blue1Brown", id: "aircAruvnKk", duration: "19:13", category: "Neural networks" },
  { title: "CS229 · Building large language models", source: "Stanford Online", id: "9vM4p9NN0Ts", duration: "1:20:38", category: "Transformers" },
  { title: "Gradient descent, how neural networks learn", source: "3Blue1Brown", id: "IHZwWFHWa-w", duration: "21:00", category: "Optimization" },
];

function Header({ page, setPage }: { page: Page; setPage: (page: Page) => void }) {
  const [open, setOpen] = useState(false);
  const links: Array<[Page, string]> = [["home", "Research home"], ["cases", "Case workspace"], ["videos", "ML library"], ["images", "Visual atlas"], ["methods", "Notes & sources"]];
  return <header className="lab-header"><div className="lab-header-inner"><button className="lab-brand" onClick={() => setPage("home")}><span className="brand-symbol"><Microscope size={18} /></span><span><strong>CaPS</strong><small>PATHOLOGY SYSTEMS LAB</small></span></button><button className="lab-menu" onClick={() => setOpen(!open)}>{open ? <X size={19} /> : <Menu size={19} />}</button><nav className={open ? "lab-nav open" : "lab-nav"}>{links.map(([id, label]) => <button key={id} className={page === id ? "active" : ""} onClick={() => { setPage(id); setOpen(false); }}>{label}</button>)}</nav><div className="header-status"><span /> DEMO NODE / ONLINE</div></div></header>;
}

function Photo({ src, alt, className = "" }: { src: string; alt: string; className?: string }) { return <img className={`real-photo ${className}`} src={src} alt={alt} loading="lazy" />; }

function HomePage({ setPage }: { setPage: (page: Page) => void }) {
  const cases = trpc.cases.list.useQuery();
  const tileRequest = trpc.tiles.request.useMutation({ onSuccess: result => toast.success(`Tile ${result.tileId} rendered · ${result.bytesReceived.toLocaleString()} bytes`), onError: error => toast.error(error.message) });
  const leadCase = cases.data?.[0];
  return <main className="lab-main">
    <section className="lab-hero"><div className="hero-photo"><Photo src={photos.lab} alt="Researchers working at a machine-learning laboratory workstation" /></div><div className="hero-overlay" /><div className="lab-container hero-content"><div className="hero-kicker"><span className="kicker-line" /> COMPUTATIONAL PATHOLOGY / 2026</div><h1>Read the slide.<br /><em>Keep the evidence.</em></h1><p className="hero-lede">CaPS is a semantic pathology workspace for navigating whole-slide images without moving the whole image. Explore tissue structure first, then retrieve the pixels that matter.</p><div className="hero-buttons"><button className="lab-button bright" onClick={() => setPage("cases")}>Open case workspace <ArrowUpRight size={15} /></button><button className="lab-button ghost" onClick={() => setPage("videos")}>Explore ML library <Play size={14} /></button></div><div className="hero-foot"><span><Check size={13} /> research prototype</span><span><Check size={13} /> no clinical claims</span><span><Check size={13} /> public demo data</span></div></div><div className="hero-index">01 / 05<br /><span>SEMANTIC PATHOLOGY</span></div></section>
    <section className="lab-container metric-strip"><div><b>2.84 GB</b><span>raw slide sample</span></div><div><b>1.82 MB</b><span>evidence capsule</span></div><div><b>2,980</b><span>semantic patches</span></div><div><b>182 ms</b><span>replayed tile request</span></div></section>
    <section className="lab-container section-dark"><div className="section-label">THE WORKFLOW <span>01 — 04</span></div><div className="section-title-row"><h2>From pixels to <em>meaning</em></h2><p>A focused interface for the parts of a pathology pipeline that need to stay inspectable.</p></div><div className="workflow-grid">{[["01", "Ingest", "Whole-slide metadata, coordinates and source provenance."], ["02", "Encode", "Patch embeddings from a pathology foundation model."], ["03", "Capsule", "Prototype assignments compressed into an evidence layer."], ["04", "Retrieve", "A bounded raw tile request after semantic navigation."]].map(([n, title, text]) => <article key={n} className="workflow-card"><span>{n}</span><h3>{title}</h3><p>{text}</p><ChevronRight size={17} /></article>)}</div></section>
    <section className="split-feature"><div className="lab-container split-grid"><div className="split-copy"><div className="section-label">CASE / {leadCase?.caseId ?? "CASE-042"}</div><h2>A visual atlas for every <em>decision.</em></h2><p>The semantic view keeps spatial context, morphology clusters and source metadata together. Request a tile only when the region earns a closer look.</p><div className="feature-meta"><span><b>{leadCase?.patchCount?.toLocaleString() ?? "2,980"}</b> patches</span><span><b>{leadCase?.capsuleSize ?? "1.82 MB"}</b> capsule</span></div><button className="text-link" onClick={() => setPage("cases")}>Enter the case workspace <ArrowUpRight size={15} /></button></div><div className="slide-photo"><Photo src={photos.slide} alt="Whole-slide digital pathology scan" /><span className="photo-label">WHOLE-SLIDE REFERENCE / PUBLIC SOURCE</span><div className="scan-box" /></div></div></section>
    <section className="lab-container lab-photo-band"><div className="photo-band-image"><Photo src={photos.server} alt="Real server room used as a visual reference for compute infrastructure" /></div><div className="photo-band-copy"><div className="section-label">THE COMPUTE LAYER</div><h2>Move less data.<br /><em>See more context.</em></h2><p>CaPS uses a capsule-first interaction model: metadata and semantic structure travel before raw pixels. This is a research direction, not a clinical product.</p><div className="band-actions"><button className="lab-button bright" onClick={() => leadCase && tileRequest.mutate({ caseId: leadCase.caseId, tileId: "tile-042", x: 3842, y: 2991, width: 224, height: 224, level: 0 })}>Request demo tile</button><button className="text-link" onClick={() => setPage("methods")}>Read the method notes <ArrowUpRight size={15} /></button></div></div></section>
    <section className="lab-container atlas-callout"><div><div className="section-label">RESEARCH LIBRARY</div><h2>Real images. Real references.<br /><em>Clear labels.</em></h2></div><div className="atlas-actions"><button onClick={() => setPage("images")}><ImageIcon size={16} /> Visual atlas <ArrowUpRight size={14} /></button><button onClick={() => setPage("videos")}><BookOpen size={16} /> 124 ML resources <ArrowUpRight size={14} /></button></div></section>
  </main>;
}

function CasesPage() { const query = trpc.cases.list.useQuery(); const items = query.data ?? []; return <main className="lab-container inner-page"><div className="inner-head"><div><div className="section-label">CASE WORKSPACE</div><h1>Cases, capsules,<br /><em>and provenance.</em></h1><p>Public, de-identified demo artifacts for semantic pathology review.</p></div><button className="lab-button bright" onClick={() => toast("Slide ingestion is ready for a connected WSI source")}>+ Ingest a slide</button></div><div className="case-table"><div className="case-table-head"><span>CASE</span><span>SLIDE</span><span>SOURCE</span><span>STATUS</span><span>PAYLOAD</span></div>{query.isLoading ? <div className="table-empty">Loading case metadata…</div> : query.error ? <div className="table-empty danger">Unable to load case metadata. Refresh to try again.</div> : items.length === 0 ? <div className="table-empty">No cases have been added yet.</div> : items.map(item => <div className="case-table-row" key={item.caseId}><div><b>{item.caseId}</b><small>{item.updatedAt.toLocaleDateString()}</small></div><span>{item.slideId}</span><span>{item.source}</span><span className={`state ${item.status}`}>{item.status}</span><span><b>{item.capsuleSize}</b><small>{item.patchCount.toLocaleString()} patches</small></span></div>)}</div><div className="integrity"><Check size={14} /> Demo metadata and replayed values are labeled. No patient data, diagnostic output, or treatment recommendation is present.</div></main>; }

function VideosPage() { const [selected, setSelected] = useState(featuredVideos[0]); const [search, setSearch] = useState(""); const filtered = useMemo(() => videoResources.filter(item => item.title.toLowerCase().includes(search.toLowerCase())), [search]); return <main className="lab-container inner-page"><div className="inner-head"><div><div className="section-label">KNOWLEDGE LIBRARY / MACHINE LEARNING</div><h1>Watch how the<br /><em>models learn.</em></h1><p>{videoResources.length} technical resources, curated for the CaPS research workflow.</p></div><div className="resource-number">{videoResources.length}<small>indexed resources</small></div></div><div className="video-stage"><div className="video-frame"><iframe src={`https://www.youtube.com/embed/${selected.id}?rel=0`} title={selected.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /><div className="video-caption"><span>{selected.category}</span><b>{selected.title}</b><small>{selected.source} · {selected.duration}</small></div></div><aside className="lecture-list"><div className="list-heading">FEATURED / 03</div>{featuredVideos.map(item => <button className={item.id === selected.id ? "lecture active" : "lecture"} key={item.id} onClick={() => setSelected(item)}><span><Play size={12} /></span><b>{item.title}</b><small>{item.source} · {item.duration}</small></button>)}</aside></div><label className="dark-search"><Search size={16} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search the full resource index" /></label><div className="resource-grid">{filtered.slice(0, 36).map((item, index) => <button className="resource-card" key={`${item.title}-${index}`} onClick={() => toast("Catalog entry noted. Select a featured lecture for verified inline playback.")}><span>{String(index + 1).padStart(3, "0")}</span><b>{item.title}</b><small>{item.category} · {item.source}</small></button>)}</div></main>; }

function ImagesPage() { const refs = [{ src: photos.lab, title: "ML lab / human-in-the-loop research", source: "Unsplash image search result", href: "https://unsplash.com/" }, { src: photos.server, title: "Compute infrastructure / server room", source: "Unsplash image search result", href: "https://unsplash.com/" }, { src: photos.slide, title: "Whole-slide digital pathology scan", source: "University of Florida Molecular Pathology Core", href: "https://pathology.ufl.edu/" }]; return <main className="lab-container inner-page"><div className="inner-head"><div><div className="section-label">VISUAL ATLAS / SOURCE IMAGERY</div><h1>See the work<br /><em>behind the data.</em></h1><p>Real photographs and public scientific references replace placeholder illustrations throughout the research library.</p></div><div className="resource-number">20<small>scientific references</small></div></div><div className="photo-grid">{refs.map((item, index) => <article className={index === 0 ? "photo-card large" : "photo-card"} key={item.title}><Photo src={item.src} alt={item.title} /><div className="photo-card-copy"><span>0{index + 1} / SOURCE IMAGE</span><h3>{item.title}</h3><p>{item.source}</p><a href={item.href} target="_blank" rel="noreferrer">View source <ExternalLink size={13} /></a></div></article>)}</div><div className="resource-grid image-index">{imageResources.slice(0, 12).map((item, index) => <a className="resource-card" href={item.href} target="_blank" rel="noreferrer" key={item.title}><span>{String(index + 1).padStart(3, "0")}</span><b>{item.title}</b><small>{item.category} · {item.source}</small></a>)}</div></main>; }

function MethodsPage() { const methods = [["UNI", "Pathology foundation model reference", "https://github.com/mahmoodlab/UNI", Microscope], ["PANTHER / MMP", "Morphological prototype modeling reference", "https://github.com/mahmoodlab/PANTHER", FlaskConical], ["MONAI", "Medical imaging deployment ecosystem", "https://monai.io/", Database], ["PUBLIC WSI", "Whole-slide image source index", "https://commons.wikimedia.org/wiki/Category:Whole_slide_images", FileText]] as const; return <main className="lab-container inner-page"><div className="section-label">METHOD NOTES / SOURCES</div><h1>What is real.<br /><em>What is replayed.</em></h1><p className="method-intro">CaPS is an inspectable research prototype. Every visual, metric and system claim is either sourced, implemented, or explicitly labeled as replay data.</p><div className="method-grid"><article><Server size={18} /><h3>Capsule-first transport</h3><p>Metadata and semantic structure are prioritized before bounded raw tile retrieval.</p></article><article><FlaskConical size={18} /><h3>Prototype morphology</h3><p>Cluster and embedding concepts are shown as research references, not clinical outputs.</p></article><article><ImageIcon size={18} /><h3>Source imagery</h3><p>Real lab, compute and pathology imagery is labeled with its public source.</p></article></div><div className="method-list">{methods.map(([name, description, href, Icon]) => <a href={href} target="_blank" rel="noreferrer" key={name}><span><Icon size={15} /></span><b>{name}</b><small>{description}</small><ArrowUpRight size={15} /></a>)}</div></main>; }

export default function Home() { const [page, setPage] = useState<Page>("home"); return <div className="lab-app"><Header page={page} setPage={setPage} />{page === "home" && <HomePage setPage={setPage} />}{page === "cases" && <CasesPage />}{page === "videos" && <VideosPage />}{page === "images" && <ImagesPage />}{page === "methods" && <MethodsPage />}<footer className="lab-footer"><div className="lab-container"><span>CaPS / CANCER PATHOLOGY SEMANTIC CAPSULE</span><span>RESEARCH PROTOTYPE · PUBLIC DEMO DATA · NO PHI</span></div></footer></div>; }
