import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowDown, ArrowUpRight, Box, BrainCircuit, CheckCircle2, ChevronRight, CircleDot, Code2, Database, Download, Gauge, GitBranch, Grid3X3, Layers3, Maximize2, Microscope, Network, Pause, Play, Radio, RefreshCw, Search, Server, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Terminal, Timer, Upload, Wifi, X, ZoomIn, ZoomOut } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

type Focus = "command" | "cases" | "model" | "prototypes" | "embeddings" | "capsule" | "network" | "observability" | "research" | "videos" | "images";

type Prototype = { id: number; label: string; count: number; similarity: number; color: string; x: number; y: number; footprint: string };
const prototypes: Prototype[] = [
  { id: 1, label: "stromal / pale", count: 342, similarity: .94, color: "#4f9aa0", x: 14, y: 22, footprint: "upper-left" },
  { id: 7, label: "epithelial / dense", count: 516, similarity: .91, color: "#d19a53", x: 31, y: 39, footprint: "central band" },
  { id: 12, label: "lymphoid / compact", count: 287, similarity: .88, color: "#bd6c74", x: 58, y: 25, footprint: "right island" },
  { id: 17, label: "necrotic / sparse", count: 164, similarity: .82, color: "#8f74bb", x: 71, y: 67, footprint: "lower-right" },
  { id: 23, label: "vascular / lumen", count: 89, similarity: .79, color: "#5e8bc0", x: 42, y: 76, footprint: "lower-center" },
];
const pipeline = ["WSI_INGEST", "TILING_COMPLETE", "ENCODER_INIT", "EMBEDDING_COMPLETE", "PROTOTYPES_READY", "CAPSULE_CREATED", "SEMANTIC_VIEW_READY", "TILE_REQUESTED"];
const events = [
  ["20:18:04.221", "WSI_INGEST", "2.84 GB source registered", "READY"],
  ["20:18:05.008", "TILING_COMPLETE", "2,980 patches / level 0–3", "READY"],
  ["20:18:05.742", "ENCODER_INIT", "UNI · fp16 · cuda:0", "READY"],
  ["20:18:12.664", "EMBEDDING_COMPLETE", "2,980 × 1,024 vector", "READY"],
  ["20:18:13.012", "PROTOTYPES_READY", "32 centroids / k-means++", "READY"],
  ["20:18:13.211", "CAPSULE_CREATED", "1.82 MB semantic payload", "READY"],
];
const modelStats = [["MODEL", "UNI / pathology encoder"], ["VERSION", "v1.1 · research checkpoint"], ["INPUT", "H&E RGB tiles"], ["PATCH SIZE", "224 × 224 px"], ["OBJECTIVE", "20× / 0.75 NA"], ["EMBEDDING", "1,024 dimensions"], ["DEVICE", "cuda:0 · 23.4 GB"], ["PRECISION", "float16"], ["BATCH", "64 tiles"], ["THROUGHPUT", "412 tiles / sec"], ["LATENCY", "182 ms p95"]];
const focusLabels: Record<Focus, string> = { command: "COMMAND CENTER", cases: "CASE WORKSPACE", model: "MODEL CENTER", prototypes: "PROTOTYPE LAB", embeddings: "EMBEDDING LAB", capsule: "EVIDENCE CAPSULE", network: "NETWORK LAB", observability: "OBSERVABILITY", research: "RESEARCH ROADMAP", videos: "ML VIDEO OBSERVATORY", images: "SCIENTIFIC VISUALIZATION" };
const railLinks: Array<[string, string, React.ElementType]> = [["/", "Command", Gauge], ["/cases/CASE-042", "Case viewer", Microscope], ["/model", "Model center", BrainCircuit], ["/prototypes", "Prototypes", Layers3], ["/embeddings", "Embeddings", GitBranch], ["/capsule", "Capsule", Box], ["/network", "Network", Network], ["/observability", "Telemetry", Activity]];

function MiniSpark({ color = "#65c5ba", points = "0,30 10,22 20,26 30,9 40,16 50,7 60,14 70,2 80,8 90,0" }: { color?: string; points?: string }) { return <svg className="mini-spark" viewBox="0 0 90 34" aria-hidden="true"><polyline points={points} fill="none" stroke={color} strokeWidth="2" /></svg>; }
function Metric({ label, value, meta, color = "teal" }: { label: string; value: string; meta: string; color?: string }) { return <div className="metric"><span className="metric-label">{label}</span><b className={`metric-value ${color}`}>{value}</b><small>{meta}</small></div>; }
function Status({ children, tone = "ok" }: { children: React.ReactNode; tone?: "ok" | "warn" | "muted" }) { return <span className={`status ${tone}`}><i />{children}</span>; }

function SpatialViewer({ selected, setSelected, mode, setMode, zoom, setZoom }: { selected: Prototype; setSelected: (p: Prototype) => void; mode: string; setMode: (m: string) => void; zoom: number; setZoom: (z: number) => void }) {
  return <section className="viewer-panel panel-grid-bg">
    <div className="panel-head"><div><span className="section-kicker"><CircleDot size={12} /> SPATIAL SEMANTIC MAP</span><h2>WSI / {mode.toUpperCase()} LAYER</h2></div><div className="viewer-tools"><button onClick={() => setZoom(Math.min(1.35, zoom + .1))}><ZoomIn size={14} /></button><button onClick={() => setZoom(Math.max(.75, zoom - .1))}><ZoomOut size={14} /></button><button><Maximize2 size={14} /></button></div></div>
    <div className="mode-tabs">{["RAW", "SEMANTIC", "HYBRID"].map(m => <button className={mode === m ? "active" : ""} onClick={() => setMode(m)} key={m}>{m}</button>)}<span className="coord-readout">x 4,842 · y 2,991 · L0 · 224px</span></div>
    <div className="spatial-canvas" style={{ "--viewer-scale": zoom } as React.CSSProperties}>
      <div className="wsi-underlay" />
      <div className="wsi-grid" />
      {prototypes.map(p => <button key={p.id} className={`semantic-region ${selected.id === p.id ? "selected" : ""}`} style={{ left: `${p.x}%`, top: `${p.y}%`, background: mode === "RAW" ? "rgba(238,221,194,.22)" : `${p.color}b8`, borderColor: p.color }} onClick={() => setSelected(p)} title={`Prototype ${p.id} · ${p.label}`}><span>{p.id}</span><i style={{ background: p.color }} /></button>)}
      <div className="viewer-crosshair" />
      <span className="canvas-label top-left">WSI-HE-0007 / LEVEL 0</span><span className="canvas-label bottom-right">{mode === "RAW" ? "RAW TILE COMPOSITE" : "SEMANTIC OVERLAY · PROTOTYPE MASKS"}</span>
    </div>
    <div className="viewer-footer"><span><Grid3X3 size={12} /> 2,980 tiles indexed</span><span><span className="legend-dot teal" /> tissue <span className="legend-dot amber" /> prototype {selected.id} <span className="legend-dot purple" /> selected region</span><span>scale {Math.round(zoom * 100)}%</span></div>
  </section>;
}

function PrototypeStrip({ selected, setSelected }: { selected: Prototype; setSelected: (p: Prototype) => void }) { return <section className="panel prototype-panel"><div className="panel-head compact"><div><span className="section-kicker"><Layers3 size={12} /> MORPHOLOGY PROTOTYPES</span><h2>Centroid index / k = 32</h2></div><button className="ghost-button">OPEN LAB <ArrowUpRight size={12} /></button></div><div className="prototype-grid">{prototypes.map(p => <button className={`prototype-cell ${selected.id === p.id ? "selected" : ""}`} key={p.id} onClick={() => setSelected(p)}><div className="proto-swatch" style={{ background: p.color }}><span>{p.id}</span></div><div><b>P-{String(p.id).padStart(2, "0")}</b><small>{p.count} tiles · {(p.similarity * 100).toFixed(0)}%</small></div></button>)}</div></section>; }

function EmbeddingPlot({ selected, setSelected }: { selected: Prototype; setSelected: (p: Prototype) => void }) { return <div className="embedding-plot"><div className="plot-axis x" /><div className="plot-axis y" />{Array.from({ length: 42 }, (_, i) => { const p = prototypes[i % prototypes.length]; const left = (12 + ((i * 17) % 76)); const top = (10 + ((i * 29) % 76)); return <button key={i} className={`embedding-point ${selected.id === p.id ? "selected" : ""}`} style={{ left: `${left}%`, top: `${top}%`, background: p.color }} onClick={() => setSelected(p)} />; })}<span className="axis-label x-label">PC1 / 36.2%</span><span className="axis-label y-label">PC2 / 18.7%</span></div>; }

function BottomInspector({ selected, requestTile, requested }: { selected: Prototype; requestTile: () => void; requested: boolean }) { return <div className="inspector-grid"><div className="inspector-block"><span className="section-kicker">SELECTED PROTOTYPE</span><div className="selected-proto"><div className="proto-swatch large" style={{ background: selected.color }}><span>{selected.id}</span></div><div><h3>P-{String(selected.id).padStart(2, "0")} / {selected.label}</h3><p>Centroid similarity <b>{selected.similarity.toFixed(2)}</b> · {selected.count} assignments · {selected.footprint}</p></div></div></div><div className="inspector-block tile-inspector"><span className="section-kicker">TILE INSPECTOR</span><div className="tile-line"><b>xy:{selected.x * 100 | 0},{selected.y * 100 | 0}</b><span>level 0 · 224×224</span><Status tone={requested ? "ok" : "muted"}>{requested ? "RENDERED" : "READY"}</Status></div><button className="request-button" onClick={requestTile}><Radio size={13} /> REQUEST RAW TILE <ChevronRight size={13} /></button></div></div>; }

export default function WorkbenchPage({ focus = "command" }: { focus?: Focus }) {
  const [selected, setSelected] = useState(prototypes[3]);
  const [mode, setMode] = useState("SEMANTIC");
  const [zoom, setZoom] = useState(1);
  const [demoStep, setDemoStep] = useState(focus === "command" ? 6 : 7);
  const [running, setRunning] = useState(false);
  const [requested, setRequested] = useState(false);
  const [query, setQuery] = useState("");
  const cases = trpc.cases.list.useQuery();
  const request = trpc.tiles.request.useMutation({ onSuccess: d => { setRequested(true); toast.success(`TILE_RENDERED · ${d.bytesReceived.toLocaleString()} bytes · ${d.latencyMs} ms`); }, onError: e => toast.error(e.message) });
  const caseId = cases.data?.[0]?.caseId ?? "CASE-042";
  useEffect(() => { if (!running) return; const timer = window.setInterval(() => setDemoStep(s => { if (s >= pipeline.length - 1) { setRunning(false); return s; } return s + 1; }), 680); return () => window.clearInterval(timer); }, [running]);
  const runDemo = () => { setRequested(false); setDemoStep(0); setRunning(true); toast("DEMO REPLAY · deterministic pipeline started"); };
  const requestTile = () => request.mutate({ caseId, tileId: `P-${String(selected.id).padStart(2, "0")}-tile-17`, x: selected.x * 100 | 0, y: selected.y * 100 | 0, width: 224, height: 224, level: 0 });
  const filteredPrototypes = prototypes.filter(p => `${p.id} ${p.label}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="workbench">
    <div className="workbench-topbar"><Link href="/" className="lab-brand"><span><Microscope size={16} /></span><b>CaPS</b><small>semantic pathology workstation</small></Link><div className="top-context"><span>CASE <b>{caseId}</b></span><span>MODEL <b>UNI v1.1</b></span><span>MODE <b>DEMO REPLAY</b></span></div><div className="top-actions"><Status>GPU READY</Status><button className="icon-button" title="Settings"><Settings2 size={15} /></button><Link className="text-link" href="/research">RESEARCH <ArrowUpRight size={12} /></Link></div></div>
    <div className="workbench-body"><aside className="workbench-rail"><div className="rail-label">WORKSPACE</div>{railLinks.map(([href, label, Icon]) => <Link key={href} href={href} className={focusLabels[focus] === label.toUpperCase() || (focus === "command" && label === "Command") ? "active" : ""}><Icon size={15} /><span>{label}</span></Link>)}<div className="rail-divider" /><div className="rail-label">LIBRARY</div><Link href="/ml"><Radio size={15} /><span>Video observatory</span><em>124</em></Link><Link href="/atlas"><Sparkles size={15} /><span>Scientific images</span><em>24</em></Link><Link href="/research"><Search size={15} /><span>Research graph</span></Link><div className="rail-bottom"><span className="status-line"><i />api / healthy</span><span className="status-line"><i />cache / 82.4%</span></div></aside>
      <main className="workbench-main"><div className="workspace-heading"><div><span className="section-kicker">{focusLabels[focus]}</span><h1>{focus === "command" ? "Semantic review command center" : focusLabels[focus]}</h1><p>{focus === "command" ? "Trace a whole-slide image from raw tissue to a compact, requestable semantic representation." : "Inspectable research surface · all values marked demo replay where precomputed."}</p></div><div className="heading-actions"><button className="demo-button" onClick={running ? () => setRunning(false) : runDemo}>{running ? <Pause size={14} /> : <Play size={14} />} {running ? "PAUSE DEMO" : "RUN CaPS DEMO"}</button><button className="reset-button" onClick={() => { setDemoStep(0); setRequested(false); setRunning(false); }}>RESET</button></div></div>
        {focus === "model" ? <ModelPanel /> : focus === "capsule" ? <CapsulePanel /> : focus === "network" ? <NetworkPanel /> : focus === "observability" ? <ObservabilityPanel /> : focus === "research" ? <ResearchPanel /> : focus === "videos" ? <VideoPanel query={query} setQuery={setQuery} /> : focus === "images" ? <ImagePanel query={query} setQuery={setQuery} /> : <>
          <div className="metric-strip"><Metric label="RAW WSI" value="2.84 GB" meta="level 0 · 38,412 × 28,772" color="blue" /><Metric label="SEMANTIC CAPSULE" value="1.82 MB" meta="99.94% smaller representation" /><Metric label="PATCH EMBEDDINGS" value="2,980" meta="1,024D · 412 tiles/sec" color="amber" /><Metric label="NETWORK SENT" value={requested ? "148 KB" : "1.82 MB"} meta={requested ? "1 raw tile · cache hit" : "capsule only · no raw pixels"} color="purple" /><div className="metric-chart"><span>throughput / last batch</span><MiniSpark /></div></div>
          <div className="workbench-grid"><SpatialViewer selected={selected} setSelected={setSelected} mode={mode} setMode={setMode} zoom={zoom} setZoom={setZoom} /><aside className="telemetry-panel"><div className="panel-head"><div><span className="section-kicker"><Activity size={12} /> LIVE TELEMETRY</span><h2>Pipeline state</h2></div><span className="live-pill"><i />LIVE</span></div><div className="pipeline">{pipeline.map((step, i) => <div className={`pipeline-step ${i < demoStep ? "done" : i === demoStep ? "current" : ""}`} key={step}><span>{i < demoStep ? <CheckCircle2 size={13} /> : i === demoStep && running ? <RefreshCw className="spin" size={13} /> : <CircleDot size={13} />}</span><div><b>{step}</b><small>{i < demoStep ? events[Math.min(i, events.length - 1)]?.[0] : i === demoStep ? "processing..." : "queued"}</small></div></div>)}</div><div className="telemetry-foot"><span>event rate <b>4.2 / sec</b></span><span>errors <b className="good">0.00%</b></span></div></aside></div>
          <div className="bottom-grid"><PrototypeStrip selected={selected} setSelected={setSelected} /><div className="panel embedding-panel"><div className="panel-head compact"><div><span className="section-kicker"><GitBranch size={12} /> LATENT REPRESENTATION</span><h2>Embedding projection / PCA</h2></div><span className="panel-note">2,980 points</span></div><EmbeddingPlot selected={selected} setSelected={setSelected} /><div className="plot-footer"><span>selected → P-{String(selected.id).padStart(2, "0")} → x:{selected.x * 100 | 0}, y:{selected.y * 100 | 0}</span><Link href="/embeddings">OPEN EMBEDDING LAB <ArrowUpRight size={11} /></Link></div></div></div>
          <BottomInspector selected={selected} requestTile={requestTile} requested={requested} />
        </>}
        <div className="execution-band"><div><span className="section-kicker"><Terminal size={12} /> EVENT STREAM</span><h2>Inspectable execution trace</h2></div><div className="event-table">{events.slice(0, 4).map(e => <div className="event-row" key={e[0]}><code>{e[0]}</code><b>{e[1]}</b><span>{e[2]}</span><Status>{e[3]}</Status></div>)}{requested && <div className="event-row new"><code>20:18:16.481</code><b>TILE_RENDERED</b><span>P-{String(selected.id).padStart(2, "0")} · 148 KB · cache hit</span><Status>READY</Status></div>}</div></div>
      </main></div><div className="workbench-statusbar"><span><Wifi size={12} /> gateway connected</span><span><Database size={12} /> capsule checksum 8c7a…f1e2</span><span><Timer size={12} /> last event 182ms ago</span><span className="statusbar-right">CaPS v0.4.2 · demo artifacts · no PHI</span></div>
  </div>;
}

function ModelPanel() { return <div className="focus-layout"><div className="panel model-architecture"><span className="section-kicker"><BrainCircuit size={12} /> FOUNDATION MODEL STACK</span><h2>UNI / pathology encoder</h2><div className="stack-flow">{["H&E TILES", "NORMALIZE", "UNI v1.1", "1,024D EMBEDDING", "K-MEANS / K=32", "CAPSULE PAYLOAD"].map((x, i) => <div key={x} className="stack-node"><span>{String(i + 1).padStart(2, "0")}</span><b>{x}</b>{i < 5 && <ArrowDown size={14} />}</div>)}</div></div><div className="panel spec-panel"><span className="section-kicker">CHECKPOINT SPECIFICATION</span>{modelStats.map(([a, b]) => <div className="spec-row" key={a}><span>{a}</span><b>{b}</b></div>)}</div><div className="panel wide-panel"><div className="panel-head compact"><div><span className="section-kicker"><Gauge size={12} /> INFERENCE BENCH</span><h2>Batch execution / demo replay</h2></div><Status>STABLE</Status></div><div className="bench-bars">{[["encoder", 82, "412 tiles/s"], ["projection", 64, "18.6 ms"], ["prototype assignment", 48, "12.4 ms"], ["serialization", 23, "4.1 ms"]].map(([n, v, m]) => <div className="bench-row" key={String(n)}><span>{n}</span><div><i style={{ width: `${v}%` }} /></div><b>{m}</b></div>)}</div></div></div>; }
function CapsulePanel() { return <div className="focus-layout"><div className="capsule-hero"><div className="capsule-orbit"><div className="orbit-core"><Box size={27} /><b>CAPSULE</b><small>8c7a…f1e2</small></div><span className="orbit-dot d1" /><span className="orbit-dot d2" /><span className="orbit-dot d3" /></div><div><span className="section-kicker"><Box size={12} /> EVIDENCE CAPSULE LAB</span><h2>Semantic representation, not lossless compression.</h2><p>CaPS stores the spatial semantics needed for remote review first. Raw pixels remain selectively requestable when the reviewer chooses a coordinate.</p><Status>DEMO REPLAY / SERIALIZED</Status></div></div><div className="capsule-grid">{[["CAPSULE SIZE", "1.82 MB"], ["SLIDE SIZE", "2.84 GB"], ["ASSIGNMENTS", "2,980"], ["PROTOTYPES", "32"], ["SERIALIZATION", "msgpack + zstd"], ["VERSION", "capsule/v0.4.2"], ["CHECKSUM", "sha256 8c7a…f1e2"], ["RAW REQUESTS", "0 → selective"]].map(([a, b]) => <div className="capsule-stat" key={a}><span>{a}</span><b>{b}</b></div>)}</div><div className="panel json-panel"><div className="panel-head compact"><div><span className="section-kicker"><Code2 size={12} /> CAPSULE INSPECTOR</span><h2>semantic_payload.json</h2></div><Download size={14} /></div><pre>{`{\n  "case": "CASE-042",\n  "slide": "WSI-HE-0007",\n  "coordinate_system": "level_0",\n  "assignments": [\n    { "x": 3842, "y": 2991, "prototype": 17 },\n    { "x": 4098, "y": 2991, "prototype": 17 },\n    { "x": 4354, "y": 2991, "prototype": 07 }\n  ],\n  "embedding_dim": 1024,\n  "checksum": "8c7a…f1e2"\n}`}</pre></div></div>; }
function NetworkPanel() { return <div className="focus-layout"><div className="network-compare"><div className="network-column conventional"><span className="section-kicker">CONVENTIONAL REVIEW</span><h2>FULL WSI TRANSFER</h2><div className="transfer-bar full" /><b>2.84 GB</b><small>first review blocked on transfer</small><div className="network-arrow"><ArrowDown size={15} /></div><div className="network-state">WAITING / 43.2 min simulated</div></div><div className="network-column caps"><span className="section-kicker">CaPS REVIEW</span><h2>SEMANTIC FIRST</h2><div className="transfer-bar compact" /><b>1.82 MB</b><small>capsule available before raw pixels</small><div className="network-arrow"><ArrowDown size={15} /></div><div className="network-state ready">READY / first semantic view</div></div></div><div className="network-metrics"><Metric label="BANDWIDTH SAVED" value="99.94%" meta="capsule vs raw WSI" /><Metric label="FIRST REVIEW" value="182 ms" meta="simulated tile path" color="amber" /><Metric label="CACHE HIT RATE" value="82.4%" meta="last 128 requests" color="purple" /><Metric label="REQUEST COUNT" value="1" meta="after semantic navigation" color="blue" /></div><div className="panel waterfall"><div className="panel-head compact"><div><span className="section-kicker"><Network size={12} /> TRANSFER WATERFALL</span><h2>Selective retrieval trace</h2></div><span className="panel-note">SIMULATED LATENCY</span></div>{[["CAPSULE", 100, "1.82 MB", "0–42 ms"], ["COORDINATE RESOLUTION", 23, "0.4 KB", "43–58 ms"], ["TILE REQUEST", 12, "148 KB", "59–182 ms"], ["DECODE / RENDER", 8, "224×224", "183–191 ms"]].map(([a, w, b, c]) => <div className="waterfall-row" key={String(a)}><b>{a}</b><div><i style={{ width: `${w}%` }} /></div><span>{b}</span><code>{c}</code></div>)}</div></div>; }
function ObservabilityPanel() { return <div className="focus-layout"><div className="metric-strip big"><Metric label="PIPELINE HEALTH" value="99.98%" meta="12,480 events · 0 errors" /><Metric label="ENCODER P95" value="182 ms" meta="last batch / demo" color="amber" /><Metric label="API P95" value="46 ms" meta="tRPC / tiles.request" color="blue" /><Metric label="CACHE" value="82.4%" meta="memory + edge" color="purple" /></div><div className="panel telemetry-table"><div className="panel-head compact"><div><span className="section-kicker"><Activity size={12} /> EVENT TELEMETRY</span><h2>Execution history</h2></div><Status>NO ERRORS</Status></div>{events.concat([["20:18:15.901", "SEMANTIC_VIEW_READY", "hybrid view mounted", "READY"]]).map(e => <div className="telemetry-row" key={e[0]}><code>{e[0]}</code><b>{e[1]}</b><span>{e[2]}</span><Status>{e[3]}</Status></div>)}</div><div className="panel observability-chart"><span className="section-kicker"><Gauge size={12} /> LATENCY PROFILE</span><div className="large-chart"><MiniSpark color="#e0a45c" points="0,28 8,26 16,27 24,18 32,22 40,10 48,18 56,4 64,13 72,9 80,16 90,1" /></div><div className="chart-legend"><span>encoding <b>412/s</b></span><span>tile p95 <b>182ms</b></span><span>error rate <b>0.00%</b></span></div></div></div>; }
function ResearchPanel() { const steps = ["H&E", "CELL SEGMENTATION", "CELL GRAPH", "SPATIAL TRANSCRIPTOMICS", "MULTIMODAL FUSION", "TUMOR EVOLUTION", "UNCERTAINTY", "EXPLAINABILITY", "3D DIGITAL TWIN"]; return <div className="focus-layout"><div className="roadmap-intro"><span className="section-kicker"><Sparkles size={12} /> RESEARCH ROADMAP</span><h2>Future architecture, clearly labeled.</h2><p>These are research directions, not implemented clinical functionality. The current CaPS demo ends at semantic communication of public demo slides.</p><Status tone="warn">FUTURE / NOT CLINICAL</Status></div><div className="roadmap-flow">{steps.map((s, i) => <div className={`roadmap-step ${i < 2 ? "available" : "future"}`} key={s}><span>{String(i + 1).padStart(2, "0")}</span><b>{s}</b>{i < steps.length - 1 && <ChevronRight size={15} />}</div>)}</div><div className="panel honesty-panel"><ShieldCheck size={18} /><div><b>Scientific honesty</b><p>CaPS does not claim diagnosis, treatment recommendation, survival prediction, sensitivity, specificity, or biological meaning for unsupervised prototypes.</p></div></div></div>; }
function VideoPanel({ query, setQuery }: { query: string; setQuery: (v: string) => void }) {
  const clips = [
    { src: "/research/videos/ai-explained-short.webm", title: "Artificial intelligence / visual primer", category: "Machine Learning", duration: "00:20" },
    { src: "/research/videos/neural-network-short.webm", title: "Neural network activation field", category: "Deep Learning", duration: "00:20" },
    { src: "/research/videos/axonal-network-short.webm", title: "Network morphology / microscopy", category: "Scientific Computing", duration: "00:20" },
  ];
  const [selectedClip, setSelectedClip] = useState(0);
  const visibleClips = clips.filter(clip => `${clip.title} ${clip.category}`.toLowerCase().includes(query.toLowerCase()));
  const visibleCatalog = visibleClips.map(({ title, category, duration }) => ({ title, category, duration }));
  return <div className="focus-layout"><div className="resource-head"><div><span className="section-kicker"><Radio size={12} /> ML RESEARCH VIDEO OBSERVATORY</span><h2>124 indexed resources</h2><p>Three compact source clips are bundled locally for direct playback; the wider catalog stays searchable.</p></div><div className="resource-filters"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search titles, tags, sources" /><span>LOCAL MP4 / WEBM</span><span>NO REDIRECTS</span></div></div><div className="video-observatory"><div className="local-player"><video key={clips[selectedClip].src} controls playsInline preload="metadata" src={clips[selectedClip].src} /><div className="player-meta"><span className="local-badge"><i />SAME-ORIGIN PLAYBACK</span><h3>{clips[selectedClip].title}</h3><p>{clips[selectedClip].category} · {clips[selectedClip].duration} · bundled research artifact</p></div></div><div className="clip-queue"><div className="queue-head"><span className="section-kicker">DIRECT CLIP QUEUE</span><small>3 local assets</small></div>{clips.map((clip, i) => <button key={clip.src} className={selectedClip === i ? "active" : ""} onClick={() => setSelectedClip(i)}><span className="queue-number">{String(i + 1).padStart(2, "0")}</span><span><b>{clip.title}</b><small>{clip.category} · {clip.duration}</small></span><Play size={14} /></button>)}</div></div><div className="resource-grid">{visibleCatalog.concat(Array.from({ length: Math.max(0, 12 - visibleClips.length) }, (_, i) => ({ title: ["Attention Mechanism", "UNI Foundation Model", "WSI Transformers", "Embedding Spaces", "Digital Pathology AI", "Self-Supervised Learning"][i % 6], category: ["Transformers", "Pathology AI", "Digital Pathology", "Embeddings"][i % 4], duration: `4:${String(12 + i).padStart(2, "0")}` }))).map((clip, i) => <div className="resource-card" key={`${clip.title}-${i}`}><div className="resource-thumb"><span>{String(i + 1).padStart(3, "0")}</span><Play size={18} /></div><b>{clip.title}</b><small>{clip.category} · {clip.duration}</small><button onClick={() => toast("Indexed resource selected; direct local clips play above.")}>OPEN RESOURCE <ArrowUpRight size={11} /></button></div>)}</div></div>;
}
function ImagePanel({ query, setQuery }: { query: string; setQuery: (v: string) => void }) { return <div className="focus-layout"><div className="resource-head"><div><span className="section-kicker"><Sparkles size={12} /> SCIENTIFIC VISUALIZATION LIBRARY</span><h2>24 provenance records</h2><p>Pathology, microscopy, WSI, architecture, and spatial biology references.</p></div><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search images and concepts" /></div><div className="image-resource-grid">{["/research/whole-slide.jpg", "/research/ml-lab.jpg", "/research/server-room.jpg", "/research/whole-slide.jpg", "/research/ml-lab.jpg", "/research/server-room.jpg"].map((src, i) => <figure key={`${src}-${i}`}><img src={src} alt="Scientific research reference" loading="lazy" /><figcaption><b>{["Whole-slide pathology", "ML research laboratory", "Compute infrastructure", "Tissue morphology atlas", "Model observability", "Remote review systems"][i]}</b><small>Wikimedia Commons · public reference · provenance recorded</small></figcaption></figure>)}</div></div>; }
